version: '3'
services:
    database:
        build:
            context: ./database
        environment:
            MYSQL_ROOT_PASSWORD: ${PASSWORD}
            MYSQL_DATABASE: ${DATABASE}
        container_name: database
        ports:
        - "3500:3306"
        networks:
        - backend

    app:
        build:
            context: ./app
        container_name: golang
        ports:
        - "8000:8000"
        expose:
        - "8000"
        networks:
        - frontend
        - backend
        depends_on:
        - database

    frontend:
        build:
            context: ./front-end
        container_name: frontend
        ports:
        - "4000:80"
        networks:
        - frontend
        depends_on:
        - database
        - app

networks:
    backend:
    frontend: